### ISSUE TITLE
Are you sure button

### ISSUE THREAD

**Issue by Mstiekema** [svsticky/magnificent-sloth#31]
Confirmation button on purchase

**Comment by SaiKiranRebba** [comment]
hey @Mstiekema . I would like to work on this. Can you tell me about the requirements clearly

**Comment by Yfkesmit** [comment]
The board of SV Sticky recommends to implement this as soon as possible. Please

Kind regards Yfke

**Comment by Mstiekema** [comment]
Has been fixed in https://github.com/svsticky/magnificent-sloth/commit/c95fab800aa1378729f5a10aa7e2a59bd01d2c3e
