### ISSUE TITLE
Cache pictures

### ISSUE THREAD

**Issue by Riscky** [svsticky/magnificent-sloth#51]
Product pictures are fetched every times Mongoose loads, which is slow and error-prone.
Caching pictures locally would solve this.
I think pictures have an unique ID / path, so there should not be any gotcha's.
This might need to be fixed server-side by setting some headers, but I'm not sure

**Comment by Riscky** [comment]
See: https://www.nginx.com/blog/nginx-caching-guide/

**Comment by Phavion** [comment]
This is fixed in a PR in sadserver. However, pictures are not the only culprit. The complete product page is rendered every time someone puts their card on the reader. One should cache the product page and refresh it once a day/ on startup / one pressing a button etc.

**Comment by Riscky** [comment]
svsticky/sadserver/pull/332 has been merged, which should fix the picture caching issue. 
If issues remain with the speed of the application we should open a new issue.
