### ISSUE TITLE
Show cart with confirmation message

### ISSUE THREAD

**Issue by theHam97** [svsticky/magnificent-sloth#77]
The recently added confirmation step ensures that the customer only buys what they intended to buy. However, when this message is displayed, the customer can't easily see their cart. 
It would be beneficial to customers to have a clear overview of their cart in the confirmation message

Edit: Silvan suggested that also adding the before- and after amount on the account could be a helpful feature

**Comment by Mstiekema** [comment]
Has been fixed in https://github.com/svsticky/magnificent-sloth/commit/c95fab800aa1378729f5a10aa7e2a59bd01d2c3e
